site_name: Uni Guide
site_url: https://nikuzejl.github.io/uni-guide/#/
theme:
  name: material
  logo: images/university.png
  palette: 
    - scheme: default
      primary: blue
      accent: pink 
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      primary: blue
      accent: pink 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.instant
    - navigation.instant.preview
    - navigation.progress
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.sections

nav: 
  - General Info: index.md
  - Undergraduate: undergrad.md
  - Graduate: grad.md
  - English Tests: english-tests.md
  - Other Opportunities: 
      - US Student Visa: others/usa-student-visa.md
      - Canada Study Permit: others/canada-study-permit.md
      - Various Scholarships: others/various-scholarships.md
      - Express Entry Canada: others/other-immigration-programs.md
      - Study in France: others/france.md
      - Special fields: others/special-fields.md
  - Contact: contact.md

extra:
  favicon: images/university.png