site_name: Uni Guide
site_url: https://nikuzejl.github.io/uni-guide/#/
theme:
  name: material
  logo: images/university.png
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.instant
    - navigation.instant.preview
    - navigation.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections

nav: 
  - General Info: index.md
  - Undergraduate: undergrad.md
  - Graduate: grad.md
  - Other Opportunities: others.md
  - Contact: contact.md

extra:
  favicon: images/university.png